run:
  timeout: 5m
  go: "1.22"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  goimports:
    local-prefixes: github.com/loamss/loamss

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
