package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var (
	initDataDir string
	initForce   bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a new Loamss runtime configuration",
	Long: `Create the data directory and write a default config.yaml.

This is the first command to run after installing loamss. It is
non-interactive in v0.1 — it writes sensible defaults that you can
edit afterwards. An interactive wizard arrives in a later release.

By default, init writes to ~/.loamss/ (overridable via the
--data-dir flag or the LOAMSS_DATA_DIR environment variable).

The data directory holds the runtime's operational state — the audit
log hot store, runtime SQLite, OAuth tokens, paired-client
credentials. User content lives in the storage adapter (configured
in config.yaml), which may point anywhere.`,
	Args: cobra.NoArgs,

	// Override the root's PersistentPreRunE: init creates the config, it
	// doesn't load one. Without this override, `loamss --config <missing>
	// init` would fail in the loader before init's own logic ran.
	PersistentPreRunE: func(_ *cobra.Command, _ []string) error { return nil },

	RunE: runInit,
}

func runInit(cmd *cobra.Command, _ []string) error {
	dataDir, err := resolveInitDataDir(initDataDir)
	if err != nil {
		return err
	}
	configPath := filepath.Join(dataDir, "config.yaml")

	if err := checkExisting(configPath, initForce); err != nil {
		return err
	}

	if err := os.MkdirAll(dataDir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dataDir, err)
	}

	content := renderConfigTemplate(dataDir)
	if err := os.WriteFile(configPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", configPath, err)
	}

	_, err = fmt.Fprintf(cmd.OutOrStdout(),
		"✓ Initialized data directory: %s\n"+
			"✓ Wrote config:             %s\n\n"+
			"Next steps:\n"+
			"  loamss config show    # review the resolved config\n\n"+
			"Edit %s to customize storage, memory, models, and audit settings.\n"+
			"See https://github.com/loamss/loamss for the full spec set.\n",
		dataDir, configPath, configPath)
	return err
}

// resolveInitDataDir returns the directory init should write to, in
// precedence order: --data-dir flag > LOAMSS_DATA_DIR env > ~/.loamss.
func resolveInitDataDir(flagValue string) (string, error) {
	if flagValue != "" {
		return flagValue, nil
	}
	if v := os.Getenv("LOAMSS_DATA_DIR"); v != "" {
		return v, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".loamss"), nil
}

// checkExisting returns an error if configPath exists and force is false.
// Filesystem errors other than not-found also propagate.
func checkExisting(configPath string, force bool) error {
	_, err := os.Stat(configPath)
	switch {
	case err == nil:
		if !force {
			return fmt.Errorf("config already exists at %s (use --force to overwrite)", configPath)
		}
		return nil
	case errors.Is(err, os.ErrNotExist):
		return nil
	default:
		return fmt.Errorf("checking %s: %w", configPath, err)
	}
}

// configTemplate is the YAML written by `loamss init`. Placeholders are
// substituted by renderConfigTemplate.
const configTemplate = `# Loamss runtime configuration
# Generated by ` + "`loamss init`" + `. Edit as needed.
# Documentation: https://github.com/loamss/loamss

runtime:
  # Operational state directory (audit hot store, runtime SQLite,
  # OAuth tokens, paired-client credentials). User content lives in
  # the storage adapter, configured below.
  data_dir: {{DATA_DIR}}

  # host:port for the MCP surface and console API.
  # Default 127.0.0.1:7777 — never auto-exposes publicly.
  listen_addr: 127.0.0.1:7777

# Storage adapter — where user data lives.
# Default: encrypted local filesystem under data_dir.
# Alternatives: storage:sqlite-encrypted, storage:s3-compat, storage:postgres
storage:
  adapter: storage:fs-encrypted
  config:
    root: {{STORAGE_ROOT}}

# Memory adapter — vector store for entity resolution and semantic recall.
# Default: SQLite + sqlite-vec, paired with the local storage choice.
# Alternatives: memory:pgvector, memory:chroma, memory:qdrant
memory:
  adapter: memory:sqlite-vec
  config:
    path: {{MEMORY_PATH}}

# Model adapters — providers that organizer capsules use internally.
# Optional: Loamss runs without any model; semantic memory and organizer
# capsules degrade gracefully without one.
#
# Examples:
#   models:
#     - adapter: model:anthropic
#       config:
#         api_key_env: ANTHROPIC_API_KEY
#     - adapter: model:ollama
#       config:
#         endpoint: http://localhost:11434
models: []

# Model routing rules — see ARCHITECTURE.md §model-router.
#
# Examples:
#   routing:
#     - task: drafting
#       prefer: claude-sonnet-4.7
#     - data_class: health
#       forbidden_models: [hosted]
routing: []

# Audit log — see audit-spec.md
audit:
  hot_store_max_days: 7
  hot_store_max_mb: 1024
  redaction_level: default        # default | strict | debug

# Runtime logging (distinct from the audit log)
log:
  level: info      # debug | info | warn | error
  format: text     # text | json

# Console (optional) — opt-in web UI for managing grants, audit log,
# capsule library, paired clients, and the memory browser. Disabled
# by default; the runtime is fully usable headless via the loamss
# CLI. Set enabled: true to serve the console on the listen address.
# Implementation arrives in a later release; the setting is reserved.
# console:
#   enabled: false
#   path: /console
`

func renderConfigTemplate(dataDir string) string {
	return strings.NewReplacer(
		"{{DATA_DIR}}", dataDir,
		"{{STORAGE_ROOT}}", filepath.Join(dataDir, "storage"),
		"{{MEMORY_PATH}}", filepath.Join(dataDir, "memory.db"),
	).Replace(configTemplate)
}

func init() {
	initCmd.Flags().StringVar(&initDataDir, "data-dir", "",
		"directory to create (defaults to LOAMSS_DATA_DIR or ~/.loamss)")
	initCmd.Flags().BoolVar(&initForce, "force", false,
		"overwrite an existing config.yaml")
	rootCmd.AddCommand(initCmd)
}
